[build-system]
requires = ["setuptools>=61", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "lightning_search"
version = "0.1.0"
description = "FTS search engine with first class python bindings."
